obstacle_range: 4.0
raytrace_range: 3.5
footprint: [[-0.28, 0.19], [-0.28, -0.19], [-0.20, -0.24], [0.20, -0.24], [0.28, -0.19], [0.28, 0.19], [0.20, 0.24], [-0.20, 0.24]]
inflation_radius: 0.40

observation_sources: laser_scan_sensor #ultrasound_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan_rplidar, marking: true, clearing: true}

#ultrasound_sensor: {sensor_frame: sonar, data_type: PointCloud, topic: RosAria/sonar, marking: true, clearing: true}