obstacle_range: 5.0
raytrace_range: 4.5
footprint: [[-0.20, -0.20], [-0.20, 0.20], [0.20, 0.20], [0.20, -0.20]]
robot_radius: 0.4
inflation_radius: 0.55

observation_sources: laser_scan_sensor # ultrasound_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

# ultrasound_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}